### ISSUE TITLE
Important questoin: How to link to evidence without feature?

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#101]
Currently, the SML links to features, which, in turn, link to evidences.
How do we link to evidences without feature information?

**Comment by andrewrobertjones** [comment]
This has been discussed but presumably we didn't committ it to the spec doc. We should add a section explaining exactly this point. 

The plan is that we force SMF entries to be added (even if they only repeat the SML data largely), so there is only one route from SML (via SMF) to SME. There might be cases where this is not ideal, so we should have a 10 min conversation about this at the PSI meeting, resolve and add to the spec doc.

**Comment by andrewrobertjones** [comment]
I will add some documentation with a plot to show how to handle this
