### ISSUE TITLE
Capture mzTab flavour in the metadata section

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#102]
In order to make parsing simpler, having an mzTab-flavor key in the metadata section would help to distinguish the mzTab-m / -l / -p variant.

**Comment by oliveralka** [comment]
6.1.2: Version 
enum: e.g. 1.1.0-m

**Comment by ypriverol** [comment]
It would be great to have a semantic way of defining the versions of the file format. It can be this way: 

versions: x.y.z-flavour as proposed by @oliveralka . The _x_ corresponds to a major change in the format that affects the schema, _y_ correspond to minor improvements that enrich the schema but do not affect the schema validation (e.g adding new parameters), _z_ improvements in the documentation, examples, etc.

**Comment by andrewrobertjones** [comment]
Added to the spec doc
