### ISSUE TITLE
In the line 45. MTBLS263 should be CV param

### ISSUE THREAD

**Issue by rsalek** [HUPO-PSI/mzTab#105]
This is for MTBLS263.sdf @jmrein

**Comment by jmrein** [comment]
@rsalek It _could_ be a CV param  (MIR:00000002 I guess), but a user param is valid there. In this case, I searched a filtered local database, so the user param represents an accurate depiction of _what I actually searched_ to produce those results.  Which I think is what we want there.

**Comment by rsalek** [comment]
See #104
