### ISSUE TITLE
CV Terms for mzTab-m 2.0.0

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#108]
SEP, MS
[sample_processing](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#625-sample_processing1-n)

MS
[instrument_name](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#626-instrument1-n-name)

MS
[instrument_source](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#627-instrument1-n-source)

MS
[instrument_analyzer](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#628-instrument1-n-analyzer1-n)

MS
[instrument_detector](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#629-instrument1-n-detector)

MS
[software](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6210-software1-n)

MS
[quantification_method](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6217-quantification_method)

Any CV
[assay-custom](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6219-assay1-n-custom1-n)

MS or other CV?
[study_variable_function](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6225-study_variable_function1-n)

MS
[ms_run-format](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6229-ms_run1-n-format)

MS
[ms_run-id_format](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6230-ms_run1-n-id_format)

MS or other?
[ms_run-fragmentation_method](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6231-ms_run1-n-fragmentation_method1-n)

MS
[ms_run-hash_method](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6233-ms_run1-n-hash_method)

Any CV
[custom](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6234-custom1-n) -> arbitrary, these should not be validated

NEWT
[sample-species](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6235-sample1-n-species1-n)

BTO
[sample-tissue](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6236-sample1-n-tissue1-n)

CL
[sample-cell_type](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6237-sample1-n-cell_type1-n)

DOID
[sample-disease](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6238-sample1-n-disease1-n)

Any CV
[sample-custom](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6240-sample1-n-custom1-n) => custom should not be validated

MIRIAM or other CV?
[database](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6245-database1-n)

MS or chem-mod CV
[derivatization_agent](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6249-derivatization_agent1-n)

MS
[small_molecule-quantification_unit](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6250-small_molecule-quantification_unit)

MS
[small_molecule_feature-quantification_unit](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6251-small_molecule_feature-quantification_unit)

PRIDE or other CV
[small_molecule-identification_reliability](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6252-small_molecule-identification_reliability)
MS
[id_confidence_measure](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6253-id_confidence_measure1-n)

opt_ columns will not be part of the validation.

MS
[best_id_confidence_measure](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6314-best_id_confidence_measure)

MS
[identification_method](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6515-identification_method)

MS
[ms_level](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6516-ms_level)

MS
[id_confidence_measure](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6517-id_confidence_measure1-n)

**Comment by nilshoffmann** [comment]
@nilshoffmann check https://raw.githubusercontent.com/HUPO-PSI/mzML/master/validator/src/main/resources/ms-mapping.xml
as a reference

Paths in the object model need to be translated to xpaths in the mapping file and vice versa.

https://github.com/json-path/JsonPath might be a good starting point.

**Comment by nilshoffmann** [comment]
A draft mapping file is available here:
https://github.com/nilshoffmann/jmzTab-m/blob/master/validation/src/main/resources/mappings/mzTab-M-mapping.xml

**Comment by proccaserra** [comment]
@nilshoffmann thx for following up and sending the link. 

Following-up on my question about which Vocabularies are recommended, I noticed that 
study_variable_variation_function_may  points to MS_1002882 with one child (standard error)

study_variable_average_function_may points to MS_1002882 with one child (median)

if using STATO, one could point to:
1.  'measure of variation' (https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000028), with 5 terms

2. 'measure of central tendency' (https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000029) with 11 terms

thus having more options and without having to resubmit terms.

other STATO classes of interest could be: 'effect size estimate' (https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000085) with 16 subtypes / terms

There are of course many more terms which could be useful.
STATO is available from EBI OLS so would work with the service you described during our call.

We can distribute stato in obo format or create modules.
https://github.com/ISA-tools/stato

**Comment by nilshoffmann** [comment]
@proccaserra 
We can add those as alternative term roots in the mapping file, given that we combine with XOR, so either child of the MS terms or child of the STATO terms.

**Comment by proccaserra** [comment]
@nilshoffmann oh I see, nice one. That would be indeed a good way to go about it. thx.

**Comment by nilshoffmann** [comment]
Preliminary mapping file is available: https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/2_0-Metabolomics-Draft/mzTab_2_0-M_mapping.xml

Currently, XLMOD and STATO are missing from OLS. Once they are added, we can use them in the mapping file.

**Comment by proccaserra** [comment]
@nilshoffmann STATO is in OLS:
https://www.ebi.ac.uk/ols/ontologies/stato

only XLMOD is missing

**Comment by nilshoffmann** [comment]
@procaserra Sorry, missed that! Thanks for pointing it out!

**Comment by nilshoffmann** [comment]
All ontologies are now available via OLS.
