### ISSUE TITLE
Allow Travis access

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#114]
@ypriverol @andrewrobertjones 
We tried to set up travis CI via my own travis account, however, there still seems to be an organizational approval from HUPO-PSI. Do you know where that went to and who can cater to it?

**Comment by ypriverol** [comment]
ok, do you want me to add you to the administrative privileges

**Comment by ypriverol** [comment]
I will, give me a minute

**Comment by ypriverol** [comment]
Travis enables https://travis-ci.org/HUPO-PSI/mzTab you can check the README with the image of the status.
