### ISSUE TITLE
assay[1-n]-external_uri Example for MetaboLights

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/mzTab#117]
In https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6237-assay1-n-external_uri

we have `TODO insert example URI, Need an example to show this working. Andy Jones `.

An example URL could be the upcoming ISA-API deployed on MetaboLights,
@CS76 or @khaug might have an example once it is ready.

**Comment by nilshoffmann** [comment]
@sneumann @andrewrobertjones 
Current spec doc version links to the ISA-Tab assay file:

`

MTD assay[1]-external_uri https://www.ebi.ac.uk/metabolights/MTBLS517/files/i_Investigation.txt?STUDYASSAY=a_e04_c18pos.txt

`
I will close this for now if nobody objects.
