### ISSUE TITLE
study_variable[1-n]_average_function and study_variable[1-n]_variation_function

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/mzTab#118]
In https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/1_1-Metabolomics-Draft/mzTab_format_specification_1_1-M_draft.adoc#6242-study_variable1-n_average_function

we are looking for example terms for these functions. Candidates might come 
from STATO ontology or OBI:

https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0200119
`[STATO, OBI:0200119, median calculation, ]`

and 

https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000236
`[STATO, STATO:0000236, coefficient of variation, ]`

**Comment by nilshoffmann** [comment]
Looks good, we may revisit later, whether we want to include those terms as references in PSI-MS as well.
