### ISSUE TITLE
Resurrect col_unit elements, especially for optional columns

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#131]
In PR #124, colUnits were removed from the specification. However, for optional columns, there is currently no simple way to define which unit the values they report hold, if their column name is not specified via a CVParam. AFAIU, user params do not make sense for optional column names, thus, an optional column with a specified name can only have assigned units for the values it reports via the col_unit mechanism.

**Comment by andrewrobertjones** [comment]
So you mean have something like the following:

MTD colunit-small molecule   opt_ms_run[1]_cv_MS:MS:1002476_ion_mobility_drift_time=[UO,UO:0000031, minute,]

Yes I agree that make sense. Shall I re-instate it?

**Comment by nilshoffmann** [comment]
Yes, please. The code is still working :-)

**Comment by nilshoffmann** [comment]
Or for a simple named optional column:
`MTD	colunit-small_molecule_evidence	opt_global_mass_error=[UO, UO:0000169, parts per million, ]`

**Comment by andrewrobertjones** [comment]
Re-instated but needs a new CV term for my example to be valid, which I posted a request for

**Comment by nilshoffmann** [comment]
Fixed by #135
