### ISSUE TITLE
Should we switch to database-uri?

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#144]
We have switched to use URI consistently for all other elements. Should we also use URI instead of URL for database?
`
Description: | The URL to the database.
-- | --
Type: | URL
Mandatory | True
Example: | database[1]-url http://www.hmdb.ca/
`

**Comment by nilshoffmann** [comment]
@andrewrobertjones What is your thought on switching to URI? Is there anything that I overlook that URLs can cover what URIs cannot?

**Comment by andrewrobertjones** [comment]
Agree to switch to URI, @nilshoffmann to make the change
