### ISSUE TITLE
database-url is mandatory but has no alternative for "no database" case

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#146]
The Database URL should either be made Mandatory = false, or it should be reported as "null" just as in the case of prefix.
`
Description: | The URL to the database.
-- | --
Type: | URL
Mandatory | True
Example: | database[1]-url http://www.hmdb.ca/
`

**Comment by nilshoffmann** [comment]
I will go with the Mandatory: True but value has to be reported as "null" if not available to get forward with the validator.

**Comment by andrewrobertjones** [comment]
@nilshoffmann is going to make the minor change in the spec doc to say that null is okay for no database case
