### ISSUE TITLE
Use of identifiers.org

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#171]
Steffen flagged up on the paper that we might want to recommend the use of identifiers.org, let's discuss while the specs are under review

**Comment by nilshoffmann** [comment]
Looks like a good fit, since we are using the ontology lookup service already. 
Did Steffen suggest it for the URIs to external resources?

**Comment by nilshoffmann** [comment]
This is in the spec doc for small molecule uri as an example.

https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/2_0-Metabolomics-Draft/mzTab_format_specification_2_0-M_draft.adoc#638-uri
