### ISSUE TITLE
Posttranslational modifications with multiple sites not valid

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/mzTab#176]
Hi @andrewrobertjones @timosachsenberg : 

We have now the first submissions in mzTab. We have found that the specification is not clear when multiple sites can be associated with the same modification: 

```json
MTD     variable_mod[3]-site    N
MTD     variable_mod[3]-site    Q 
```
The previous example is failing because only one site can be associated with a modification. We can hard coded this by adding sites `comma separated` or we can accept the current version  but we need to update the jmzTab. 

We have multiple submissions in this case then feedback quick is more than welcome. 

Yasset

**Comment by jgriss** [comment]
Hi @ypriverol,

All keys in the MTD section are defined to be unique. Therefore, the search settings you show should have been reported using two separate variable_mod objects.

I personally think that this is relatively clear in the specification document but we did not add a sentence stating that all keys MUST be unique.

Maybe we should add this as a clarification?

**Comment by ypriverol** [comment]
Then, for example for phosphorylation, we should add three variable modifications because we have three main possible sites (S/T/Y)

**Comment by timosachsenberg** [comment]
Yep. I agree with Johannes.

**Comment by jgriss** [comment]
> Then, for example for phosphorylation, we should add three variable modifications because we have three main possible sites (S/T/Y)

Exactly. These are three independent objects.

**Comment by andrewrobertjones** [comment]
Agree - it's a bit clunky but it seems that each variable_mod_site combination has to be treated as a separate object

**Comment by ypriverol** [comment]
We need tom improve only the README. MaxQuant is now updating the export.

**Comment by ypriverol** [comment]
MaxQuant has been already updated. Thanks, @andrewrobertjones @timosachsenberg @jgriss for your comments.
