### ISSUE TITLE
Document software ecosystem for mzTab-M 2.0

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/mzTab#180]
Hi, we should have a README/web/wiki page documenting mzTab-M support.

* LIFS will update and finalizing the Python mzTab-M library
* LIFS will be working on implementing support for mzTab-M in LipidXplorer and LUX Score (via that Python mzTab-M library)
* LIFS plans to add export of mzTab-M from Skyline in 2020
* There is also interest from MSDK / MzMine 
* GNPS can import of mzTab-M since late last year
* MS-Dial is currently working on writing mzTab-M as output.
* XCMS has a prototype mzTab-M export

Yours, Steffen

**Comment by rsalek** [comment]
Excellent news!

**Comment by nilshoffmann** [comment]
@sneumann @rsalek I have updated the project readme file. Maybe a table layout would be more compact?

**Comment by nilshoffmann** [comment]
Updated with MS DIAL example files.
