### ISSUE TITLE
Unable to upload mzTab file on PRIDE

### ISSUE THREAD

**Issue by sid1707** [HUPO-PSI/mzTab#201]
I am trying to upload my MS/MS data on PRIDE but it is not accepting mzTab file. I have used Proteome Discoverer version 2.2 for converting .msf file to .mztab file. Following error is shown 
u.a.e.p.d.m.p.MzTabParser [MzTabParser.java:118] An error occurred while parsing a section of the mzTab file, 'Error parsing line '7' ---> unknown protocol: e'
I opened the mzTab file to see line 7 and tried removing still showing the same error. I am attaching the sample mzTab file. 
[Sample-4-NaKaMZ.zip](https://github.com/HUPO-PSI/mzTab/files/6817613/Sample-4-NaKaMZ.zip)

**Comment by nilshoffmann** [comment]
@ypriverol Have you had contact concerning this issue?

**Comment by nilshoffmann** [comment]
@sid1707 Has this issue been resolved?
