### ISSUE TITLE
One ms_run should only be associated with one fraction 

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#27]
Following up on discussions on the PSI meeting.
The specification document seems to be wrong/not clear in this regards.
Having one ms_run linking to several files is problematic because linking to source spectra is not easily possible.
Having one assay linking to multiple ms_runs might help but is currently not supported in the standard.

**Comment by timosachsenberg** [comment]
otherwise linking to source spectra is not possible

**Comment by andrewrobertjones** [comment]
Agree needs a re-work. Let's continue a single thread on the topic to solve all the problems in #26
