### ISSUE TITLE
Tag ms_run with fraction identifier

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#28]
Currently, fraction support is rather limited.
One possibility to define the fraction number would be adding additional meta data.

**Comment by timosachsenberg** [comment]
```
ms_run[1]-fraction 1
```

**Comment by andrewrobertjones** [comment]
I've started some notes in here: https://github.com/HUPO-PSI/mzTab/blob/master/specification_document/1_1_draft_specs/Version11_design_considerations.pptx about the issue, I will continue to add to the powerpoint when I get a chance with some designs of how we could make it work.

Fractionated data was supposed to be supported in mzTab 1.0 but it definitely cannot be encoded without some userParams hacks. We should fix in 1.1

**Comment by andrewrobertjones** [comment]
Closing this one - continue on #26

**Comment by rsalek** [comment]
Excellent, good the have these notes
