### ISSUE TITLE
Tag ms_run with technical replicate group

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#30]
doesn't make sense to offload this to sample annotation. correct would be to annotate this at ms_run level

**Comment by timosachsenberg** [comment]
```
ms_run[1]-technical_replicate 1
```

**Comment by andrewrobertjones** [comment]
We need to review the model for ms_run, assays, SVs etc, but I'm not sure I agree that replication is best defined at the ms_run level. In a multiplex experiment, one could have two channels (two assays) for example being technical replicates.

**Comment by timosachsenberg** [comment]
Ok, I think this probably boils down to the definition of a technical replicate. My understanding was, that a TR is really recording different MS runs with the exact same samples. Independent of beeing multiplexed or not.

**Comment by timosachsenberg** [comment]
Hi @andrewrobertjones I talked a bit to our MS guys about that. You are right that the definition is a bit blurred. My initial feeling was that software could benefit if, for example, we had a strict definition that a TR is defined as a repeated measurement of the same fractionated sample with identical treatment and multiplexing (e.g., same channel order). I think it might be worth to consider it in an update of the standard but is not that urgent.

**Comment by andrewrobertjones** [comment]
Closing, think the mzTab-M 1.1 document is clear on this point now (or will be), that tech reps are defined as assays within SV referencing the same sample, bio reps have assay within SV referencing different samples.
