### ISSUE TITLE
Simplifying columns in Protein and Peptide table around Databases

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#33]
In the metabolomics 1.1-draft, there is a plan to use a prefix system before identifiers to mark which database the given ID has come from, where the prefix is explained in the header.

Propose same change for Protein and peptide table for "Database" and "Database version".

Metadata would say following:

database[1-n]  "UniProt human"
database[1-n]-prefix  "uh"
database[1-n]-version "v82"
             ...     accession   .....
PRT              uh:P678435

At the moment, we have proposed e.g. small_molecule-database[1-n], but the model can be the same for both kinds of databases, no need to split into two models.

Further to this point, taxid and species seem to be null in almost all examples, since this information may not be available to most export software (especially with customised databases). Propose to suggest that these are optional columns or list possible species contained within database as part of the header.

**Comment by rsalek** [comment]
I can't remember all of the discussion, but wouldn't it be simpler not to create a prefix and keep it as it is, e.g. CHEBI:90283. Most tools, I believe, use a full DB identifier?

**Comment by andrewrobertjones** [comment]
These could be standardised to some extent but user-built databases are more common in proteomics, so probably still need some way of specifying non-standard prefixes

**Comment by andrewrobertjones** [comment]
Closing this issue for now. I think the system we have looks okay for metabolomics, and it can be re-open again in the future if mzTab-P 1.1 is developed.
