### ISSUE TITLE
Define terms for derivatization agents

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#38]
For GC and HPLC, derivatization is often applied in order to specifically target compounds that are otherwise hard to measure at all, being non-volatile or otherwise chemically / phyiscally suboptimally suited for the separation method and to increase ionization eﬃciency and selectivity for subsequent MS analysis [1,2].  

For GC, the primary derivatization methods are 
- acylation
- alkylation and esterification
- silylation

### Example: 
- MSTFA (N-Methyl-N-(trimethylsilyl)trifluoroacetamide), is a derivatization agent for silylation in GC applications (http://www.sigmaaldrich.com/catalog/product/sial/69479)
-- molecular weight=199.25 g/mol 
-- PubChem Substance ID 329761689
-- CAS Number 24589-78-4 
-- "modification mass" (the mass actually added to derivatized molecules, in this case k trimethylsilyl groups): k* 73,19. This could be optional, but is important to discern analytes (including groups added by derivatization) from actual metabolites (the unmodified molecule).

For HPLC, some examples can be found for the following methods:
- chiral derivatization

# References:
[1] Qi et al., Derivatization for liquid chromatography-mass spectrometry; TrAC Trends in Analytical Chemistry. 59. . 10.1016/j.trac.2014.03.013.
[2] Halket et al.; Chemical derivatization and mass spectral libraries in metabolic profiling by GC/MS and LC/MS/MS, Journal of Experimental Botany, Volume 56, Issue 410, 1 January 2005, Pages 219–243, https://doi.org/10.1093/jxb/eri069

**Comment by andrewrobertjones** [comment]
Thanks Nils. Ideally we would have a list of standard terms to put in the metadata section (6.2.50.) and in 6.5.9. derivatized_form on SME. Are you aware of a CV already in existence, should we create one, or shall we just use userParams?

**Comment by nilshoffmann** [comment]
I will check the PSI MS for adequate terms and will propose new terms here before proposing them for PSI MS. I would prefer to have official terms, since the number of different agents being used is limited.

**Comment by rsalek** [comment]
@proccaserra is working on a CV list for metabolomics. It makes sense to use the one, he is working on and not to duplicate it?

**Comment by nilshoffmann** [comment]
# Derivatization related terms
[Term]
id: MS:1XXXXXXX
name: derivatization
def: "The chemical modification of a (sample|assay|aliquot,...) prior to chromatography and / or MS application." [PSI:MS]
is_a: MS:1000857 ! run attribute

[Term]
id: MS:1XXXXXXX
name: derivatization compound
def: "The chemical compound used for derivatization." [PSI:MS]
is_a: MS:1000881 ! chemical compound
relationship: part_of MS:1XXXXXXX ! derivatization

[Term]
id: MS:1XXXXXXX
name: silylation
def: "Silylation agent. May be further specified by adding chemical compound attributes." [PSI:MS]
is_a: MS:1XXXXXXX ! derivatization compound

[Term]
id: MS:1XXXXXXX
name: methoximation
def: "Methoximation agent. May be further specified by adding chemical compound attributes." [PSI:MS]
is_a: MS:1XXXXXXX ! derivatization compound

**Comment by nilshoffmann** [comment]
Define an example with derivatized form (not the actual derivatization compound, but the functional group(s) added to the derivatized compounds). Use link to chemical compound from Chebi.

**Comment by nilshoffmann** [comment]
Extend crosslinking ontology, review terms for LC-MS derivatization.

**Comment by nilshoffmann** [comment]
Terms for GC-MS and LC-MS  derivatization will be included in an updated version of the XLMOD ontology.

**Comment by nilshoffmann** [comment]
https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/cv/XLMOD.obo
