### ISSUE TITLE
Add linkage to ISA-TAB protocols in MetaData section

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#41]
Would be good to have examples showing how the MetaData section of mztab could link to an ISA-TAB for a richer description of experimental design. @rsalek

**Comment by rsalek** [comment]
Hello @proccaserra shall we look into this?

**Comment by proccaserra** [comment]
@rsalek sure, can you send me an outline of how you think things should look like?
What does linking from MzTAB to ISA entail? is it just an address to an ISA file  or a Metabolights Accession Number?

**Comment by rsalek** [comment]
some ideas: I would imagine not duplicating ISATab in mzTab, rather 
- fetching "some" existing "limited" metadata (MD) from ISATab to mzTab
- Placeholder link for the two data formats
- Capturing complementary MD related to annotation in mzTab
..... pls add if you have suggestions

**Comment by andrewrobertjones** [comment]
Copying proposal from google doc in here:

`
MTD study-url	https://www.ebi.ac.uk/metabolights/MTBLS517
MTD study-id	MTBLS517
MTD study-id-format	[,EMBL-EBI Metabolights,https://fairsharing.org/biodbcore-000168, ]
MTD study-title	MaHPIC Experiment 04: Metabolomics from Macaca mulatta infected with Plasmodium cynomolgi B strain to produce and integrate clinical, hematological, parasitological, and omics measures of acute primary infection and relapses
MTD study-version	1.0
MTD study-format [, , ISA-Tab file,]
`

**Comment by proccaserra** [comment]
@andrewrobertjones that was my first pass at it, needs you to review if the tags I have used are legit.

**Comment by nilshoffmann** [comment]
ExternalStudy:
    description: >-
      An external study, holding e.g. detailed information about the study data and metadata. A link to an ISA-Tab file deposited at 
      MetaboLights is a good example for such a use case.
    example:
      - >-
        MTD study-url	https://www.ebi.ac.uk/metabolights/MTBLS517
        MTD study-id	MTBLS517
        MTD study-id-format	[,EMBL-EBI Metabolights,https://fairsharing.org/biodbcore-000168, ]
        MTD study-title	MaHPIC Experiment 04: Metabolomics from Macaca mulatta infected with Plasmodium cynomolgi B strain to produce and integrate clinical, hematological, parasitological, and omics measures of acute primary infection and relapses
        MTD study-version	1.0
        MTD study-format [, , ISA-Tab file,]
    required:
      - id
      - title
      - url
      - id-format
      - version
      - format
    properties:
      url:
        type: string
        format: uri
      id:
        type: string
      id-format:
        $ref: '#/definitions/Parameter'
      title:
        type: string
      version:
        type: string
      format:
        $ref: '#/definitions/Parameter'

**Comment by andrewrobertjones** [comment]
We decided to keep this really simple and just have an attribute for external_study_uri now added
