### ISSUE TITLE
Spec doc is missing text on standard numerical encoding

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#42]
| TODO Insert some text in here about standard numerical encoding, e.g.  US default style “x.x”, i.e. using a period for decimal separation and  no commas to separate thousands.
-- | --

@jmrein to look into it

**Comment by jmrein** [comment]
It's important to remember that in addition to straight decimal numbers we also have _null_ (for no data, usually where a feature hasn't been detected in a particular run but may nonetheless be present, but below LOD/LOQ), and _NaN_, in the **coeffvar_study_variable** column, where the coefficient of variance isn't calculable.

Mostly CSV leaves this undefined, quite often with reference to "whatever Excel does" (which is to interpret CSVs according to the OS region). The relevant specification ([RFC4180](https://tools.ietf.org/html/rfc4180)) mostly leaves this to the side, and doesn't define datatypes at all, simply suggesting that fields containing commas are enclosed in quotes. The [TSV specification](https://www.iana.org/assignments/media-types/text/tab-separated-values), such that it is, doesn't really add much either.

In the [W3's tabular data model sec 6.4.2](https://www.w3.org/TR/tabular-data-model#formats-for-numeric-types), the decimal separator defaults to ".", unless overridden by metadata (e.g. in a sidecar file). Which is something, but we're not allowing a metadata override. It points out that this is intended as human readable data, meaning that there is justification for allowing culture-specific variations, so there may be a case for allowing a decimal-separator metadata field if we were to follow that.

That probably leaves us to the the way numerics are defined in XML.
[xs:double](https://www.w3.org/TR/xmlschema-2/#double) covers the representation, including specifically a decimal separator as the period, but also presumes support for scientific notations and infinities. This is also problematic as it specifically defines "INF" and "-INF" as the representations for the infinities, which many double-parsers will not generally automatically accept that (Python's does, but C# and Java for example expect inconsistent, locale-specific strings outside of the context of parsing XML). So I don't think it's ideal.

So I'd just suggest going with [xs:decimal](https://www.w3.org/TR/xmlschema-2/#decimal), which is just the straightforward decimal representation. No exponents. No infinities. And definitely a period as the decimal separator.
And then noting our two legal exceptions: "NaN" for incalculable numbers, and "null" for no data.

**Comment by andrewrobertjones** [comment]
Thanks Joel, that's a great summary :-) 

Overall xs:decimal seems okay, but I personally would like to allow scientific numeric notation to be allowable, and possibly support for "INF" but I could live without that.

What do others think? Support for scientific notation is more of a display convention, so I'm prepared to be persuaded that visualisation of the data is not the job of the format. If people load a file into Excel, it will automatically switch to scientific notation I think.

**Comment by andrewrobertjones** [comment]
Agreed with xs:decimal and closed
