### ISSUE TITLE
Issues with example files

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#44]
Please post any issues you spot with examples files here

**Comment by andrewrobertjones** [comment]
There is an error in @jmrein files. They seem to be missing:

6.2.18. assay[1-n]

Lines in the MTD section, which are unique identifiers for each assay.

I guess there may be other issues we spot once we have a working validator

**Comment by proccaserra** [comment]
question about the examples: I can't seem to find any examples which would clarify the following cases (currently described in the documentation/specifications)
https://github.com/HUPO-PSI/mzTab/blob/master/specification_document/1_1_draft_specs/mzTab_format_specification_1_1-M_draft.adoc#52-recommendations-for-reporting-replicates-within-experimental-designs

1. pre-fractionation case where: "In the case of pre-fractionation into n fractions, an assay SHOULD reference n ms_runs" 

in that case, one 'sample' would point to one 'assay' that would point to several distinct 'ms_runs'

2. multiplexing case where: "multiple assays are mapped to one MS run for multiplexed techniques, along with a description of the label or tag applied"

in that case, n samples would point to n 'assays' and all these assays would point to the same 'ms_run'

hence my question: is the assay entity really needed here?

prefractionnation: 1 sample -> 1 assay -> n ms_runs ~ 1 sample -> n ms_runs
multiplexing: n samples -> n assays -> 1 ms_run ~ n sample -> 1 ms_run

its definition is somewhat unclear "assay – The application of a measurement about the sample (in this case through MS) – producing values about small molecules or lipids. One assay is typically mapped to one MS run in the case of label-free MS analysis (with no pre-fractionation) or multiple assays are mapped to one MS run for multiplexed techniques, along with a description of the label or tag applied."

What are the main attributes of an mztab 'assay' that I am missing ?

Can someone point me to mztab examples with multiplex and prefrac showing the canonical use of sample, assay and ms_run ?

**Comment by andrewrobertjones** [comment]
I'm pretty sure we don't have any examples of pre-fractionation or multiplexing available, since these are rarely (fractionation) or never (multiplexing) done, as far as I know. These structures are partly there as a hang-over from proteomics, and for future proofing. 

In pretty much all cases of mzTab for metabolomics files, assay will map to one ms_run, and thus they are near synonyms. While I agree we could remove assay, and just go with ms_run. This would further remove the model from the proteomics case (where this separation is definitely needed where mutliplexing is common), and would prevent multiplexing being developed in the future for proteomics. My preference is just to document assay better, but understand not everyone will agree. Let's discuss on the call today.

**Comment by andrewrobertjones** [comment]
Agreed to add some more text to the spec doc, to suggest that for many consumers of files, Sample descriptions and links from assays SHOULD be present.

**Comment by andrewrobertjones** [comment]
@jmrein agreed to add tech reps to the MTBLS example file

**Comment by rsalek** [comment]
Hopefully we get some data  for the case: 
prefractionnation: 1 sample -> 1 assay -> n ms_runs ~ 1 sample -> n ms_runs
