### ISSUE TITLE
How to handle multi-species ?

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzTab#46]
Both metagenomics, but also if you align files from samples from different species

Need some examples

**Comment by rsalek** [comment]
Our discussion note: We could follow what metagenomics community doing for reporting structure.  Suggestion to have some optional columns to be able to capture various species at SML level, and if possible at the feature levels/ linked via Evidence (e.g- database search e.g KEGG).  Aim for a metabolite to be assigned to a species with known biology!

**Comment by andrewrobertjones** [comment]
Added note saying to use optional columns, not a big issue for 1.1
