### ISSUE TITLE
MzTab-M: id used with different meanings throughout MzTab

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#49]
MzTab-M uses the abbreviations id and ID in many different contexts.

I first suggested renaming:
ms_run[1-n]-id_format to ms_run[1-n]-nativeID_format or just  ms_run[1-n]-nativeID
which would break compatibility with MzTab 1.0

maybe we can still check for the newly introduced ones if replacing the abbreviation is less ambiguous

**Comment by andrewrobertjones** [comment]
Nils is going to change the case of all elements to lower case throughout. We changed the docs here to make it clear that this is the native ID format.

**Comment by nilshoffmann** [comment]
@andrewrobertjones @timosachsenberg 
The only elements remaining with upper case ID are mzTab-ID and structural elements like SML_ID	SMF_ID_REFS, SMF_ID, SME_ID, SME_ID_REF and SME_ID_REF_ambiguity_code.

If there are no further objections, I will close this issue.
