### ISSUE TITLE
MTD id_confidence_measure and some important issues related to scores

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#52]
MTD id_confidence_measure could be renamed.
For one, id is used several times in mzTab in different contexts, thus it would be better to not abbreviate it.

1. Why not use identification_score?

2. Higher confidence = better, scores may also have the opposite direction e.g. lower p_value = better

3. We do not specify the direction of the score, Determining this manually may be super difficult for simple parsers (e.g., require additional fields in an obo lookup (or are we even not restricted to obo - then it would be even more difficult?)). Note: in OpenMS we made good experience with storing the score direction (higher is better / worse) along with the score type.

4. to which section is this score applied? this should be clear from the MTD entry

5. Example needs update to metabolomics use case

**Comment by andrewrobertjones** [comment]
This has been discussed at some length before so decided not to revisit, but improved documentation.
