### ISSUE TITLE
Question: at which places is polarity stored?

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#56]

**Comment by nilshoffmann** [comment]
Currently nowhere, my proposal would be to add a column scan_polarity of type UserParam / CVParam to the SMF table definition. (If we can not agree, an optional column opt_scan_polarity could be recommended)

Property | Value 
----|----
Description: | The ionization mode used for acquisition of this scan.
Type: | Parameter
Is Nullable: | FALSE 
Example: |  SFH SMF_ID … scan_polarity… <br> SMF 1 … [MS, MS:1000130, positive scan, ] … 


We did discuss in one of the meetings, whether having mixed data (e.g. positive and negative mode) within one mzTab file would be a feasible use case, but settled, afair, to keep those in separate files as a recommendation. But that still requires it to be defined somewhere.

**Comment by timosachsenberg** [comment]
Ok, thanks for clarifying. Then I would suggest to just add a parameter to the meta data section.

**Comment by andrewrobertjones** [comment]
Added at the MTD level
