### ISSUE TITLE
Specification of allowed cvParams 

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/mzTab#66]
Hi, in the mzML and other formats, we have a `mappingfile.xml`,
which specifies which CV Terms are allowed in place of some `cvParam`.
We should be able to specify that e.g. a 
https://github.com/HUPO-PSI/mzTab/blob/master/specification_document/1_1_draft_specs/mzTab_format_specification_1_1-M_draft.adoc#6217-quantification_method
must be a child of 
https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1001833

This will require a new filed in the spec doc, and the validator should check that.

Yours, Steffen

**Comment by sneumann** [comment]
So for `Type=Parameter` we would need a list (sub-table ?) of allowed 
CV Terms. As example here the allowed values for `<spectrum>` in mzML:

|termAccession|useTerm|termName|isRepeatable|allowChildren|cvIdentifierRef|
|---|---|---|---|---|---|
|MS:1000499|false|spectrum attribute|true|true|MS|
|MS:1000465|false|scan polarity|false|true|MS|

Plus 1) some way to express that these MAY, but I guess that is the same as our `Mandatory=False`
and 2) some way to express the multiplicity `cvTermsCombinationLogic="OR"`, 
but that applies more to `ParameterList`

Thoughts ? Yours, Steffen

```xml
        <CvMappingRule id="spectrum_may" cvElementPath="/mzML/run/spectrumList/spectrum/cvParam/@accession" requirementLevel="MAY" scope
Path="/mzML/run/spectrumList/spectrum" cvTermsCombinationLogic="OR">
          <CvTerm termAccession="MS:1000499" useTerm="false" termName="spectrum attribute" isRepeatable="true" allowChildren="true" cvIdentifierRef="MS"></CvTerm>
          <CvTerm termAccession="MS:1000465" useTerm="false" termName="scan polarity" isRepeatable="false" allowChildren="true" cvIdentifierRef="MS"></CvTerm>
        </CvMappingRule>
```

**Comment by sneumann** [comment]
Here is a strawman example how it might look like:
https://github.com/sneumann/mzTab/blob/8d7383b8326cb163aea82dd500ff2d79728edfa8/specification_document/1_1_draft_specs/mzTab_format_specification_1_1-M_draft.adoc#6217-quantification_method

**Comment by nilshoffmann** [comment]
What would happen with validation in case someone uses an official term from a CV that is not yet on the whitelist?
Do we need something like a spec-compliance level?

**Comment by sneumann** [comment]
Hi, I think the valuation should bark. Other software could choose to fail or warn.

---
I blame Android for the brevity and typos

**Comment by andrewrobertjones** [comment]
Discussed on call, and we agree to go forward with mapping file idea @nilshoffmann  will take this forward

**Comment by sneumann** [comment]
However not in the strawman way Steffen suggested. Instead, we try to recycle the existing mapping.xml schema known from e.g. mzML or nmrML. Nils would add a post-hoc validation to check the cvParameters. Steffen can help adding a few rules. We can then use the OpenMS CVInspector to create an HTML version of the mapping file.

**Comment by sneumann** [comment]
So if we do the mappingfile.xml approach the above example could look like the following.
Biggest question is how to specify the `cvElementPath` and scopePath. Depends a bit 
on how swagger adresses an item, correct @nilshoffmann ?
Yours, Steffen
```
 <CvMappingRule id="quantification_may" cvElementPath="/mzTab/MTD/quantification_method/Parameter/@accession" requirementLevel="MAY" scopePath="/mzTab/MTD/quantification_method" cvTermsCombinationLogic="OR">
          <CvTerm termAccession="MS:1000499" useTerm="false" termName="spectrum attribute" isRepeatable="true" allowChildren="true" cvIdentifierRef="MS"></CvTerm>
          <CvTerm termAccession="MS:1000465" useTerm="false" termName="scan polarity" isRepeatable="false" allowChildren="true" cvIdentifierRef="MS"></CvTerm>
        </CvMappingRule>
```

**Comment by nilshoffmann** [comment]
Update after call on Feb 22nd 2018:

> The idea was welcomed, however not in the strawman way Steffen suggested. Instead, we try to recycle the existing mapping.xml schema known from e.g. mzML or nmrML. Nils would add a post-hoc validation to check the cvParameters. Steffen can help adding a few rules. We can then use the OpenMS CVInspector to create an HTML version of the mapping file.

**Comment by nilshoffmann** [comment]
CvTerms are being defined / tracked in #108 
Draft implementation is available here: https://github.com/nilshoffmann/jmzTab-m/blob/master/validation/src/test/resources/mzTab-M-test-mapping.xml

**Comment by nilshoffmann** [comment]
@sneumann 
Please see PR #149  for details

**Comment by nilshoffmann** [comment]
Mapping file has been included in the mzTab repository:
https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/2_0-Metabolomics-Draft/mzTab_2_0-M_mapping.xml

jmztabm accepts mapping files following this schema for semantic validation as of version 0.9.5.
