### ISSUE TITLE
Handling / Reporting of multiple adduct masses in exp_mass_to_charge

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#71]
From a recent Email exchange with Jürgen:
> I have question to the summary section. I am referring to the example MTBLS263.mztab. There, in the
> 
> first line of the summary section, is Creatinine found with the SML_ID 469. As far as I can see, this molecule
> has been found by [M+H]+ and [M+Na]+ adducts, and has a theoretical mass of 113.0589. However,
> there is a column “exp_mass_to_charge”, which I assume is the experimental mass to charge ratio.
> 
> How is this value calculated when there is more than one adduct? Is it the mean of the neutral masses
> of both adducts? Or is it weighted mean according to the abundance of the found hits?

Quoting the draft 1.1 standard:

> The experimental mass to charge of the small molecule’s primary adduct form (e.g. mean m/z across assays), assumed by default to be the protonated (positive mode) or de-protonated (negative mode), otherwise the first reported adduct under the adduct ions column. For GC-MS approaches, this MAY be the m/z of the ion used for quantification.

We could consider to also allow multiple masses in this field, each separated by '|', following the same order as in adduct_ions.

For the Example, MTBLS263.mztab, there seems to be an inconsistency regarding exp_mass_to_charge:

> According to the definition you sent me, it looks like the protonated form
has to be reported in the MTBLS263 example in  in that column which would be around 114 m/z,
> however, a value of 113.0582 is reported which can only be the neutral mass. 

I would argue, that exp_mass_to_charge should only report the actually measured mass (adducts, derivatized ...)

**Comment by jmrein** [comment]
Yeah, looks like I've put the derived neutral mass in there instead. The exp_mass_to_charge values in the SMF table look right though. I'll go through that and make some omnibus changes this afternoon or tonight or something.
