### ISSUE TITLE
quantificiation_method need update to metabolomics

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#80]
currently contains iTRAQ and SRM example

**Comment by nilshoffmann** [comment]
See lipidomics example file.

**Comment by andrewrobertjones** [comment]
I will check this in the spec doc

**Comment by nilshoffmann** [comment]
Updated to 
`
MTD quantification_method [MS, MS:1001834, LC-MS label-free quantitation analysis, ]
MTD quantification_method [MS, MS:1001838, SRM quantitation analysis, ]
....
`
