### ISSUE TITLE
Remove all occurances where retention time unit is set to minutes

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#83]
We agreed in the spec that seconds are mandatory.

Occurances of e,g, #MTD colunit-small_molecule retention_time=[UO,UO:0000031, minute,]#
should be changed to something different (to explain the unit concept).

**Comment by timosachsenberg** [comment]
in that line: colunit-small_molecule does not contain a proper example

**Comment by nilshoffmann** [comment]
Set field as retention_time_in_seconds (summary and feature level).

**Comment by timosachsenberg** [comment]
hi can you link to the PR or commit that addressed that issue? Sorry, I can't find it.
