### ISSUE TITLE
MzTab-M: mzTab-ID is mandatory. Example is missing that indicates how the string can/should be choosen.

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#84]

**Comment by ypriverol** [comment]
@timosachsenberg what is this?

**Comment by timosachsenberg** [comment]
This is a minor issue of mztab-M but I think it would be a good idea to provide a good example.
Especially as the one in the spec doc refers to a proteomics example.

https://github.com/HUPO-PSI/mzTab/blob/master/specification_document/1_1_draft_specs/mzTab_format_specification_1_1-M_draft.adoc#622-mztab-id

**Comment by andrewrobertjones** [comment]
This looks to have been updated in the spec doc as a MTBL example is given
