### ISSUE TITLE
CRITICAL: link to quantification channel

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#89]
related to: https://github.com/HUPO-PSI/mzTab/issues/26 
When assays are quantified, it is crucial to define the channels used to derive the assay quant value.
In the proteomics part, we have the meta value "quantification_reagent" to specify which channel (e.g. a light or heavy (or TMT) channel) of a ms_run was grouped in an assay.
This seems to be missing from the metabolomics part.

**Comment by andrewrobertjones** [comment]
We don't think this is needed for metabolomics, where in effect only label-free is supported.

**Comment by timosachsenberg** [comment]
one common use-case is absolute quantification using labeled standards
