### ISSUE TITLE
evidence_unique_ID clarify how "fragment spectrum, RT and m/z pair, isotope profile" is used 

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#91]
The sentence "e.g. fragment spectrum, RT and m/z pair, isotope profile that was used for the identification process" is vague. It is not clear what is meant / how this should look like in an actual mzTab.
The example is not very clear in that regards and needs to be extended.

**Comment by andrewrobertjones** [comment]
@jmrein The attribute is wrongly named in the file, it should be: evidence_unique_ID
