### ISSUE TITLE
Reporting of mixed adduct evidence / features and summary entries

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/mzTab#95]
How should we handle mixed adduct reporting? 
Is the example in https://github.com/HUPO-PSI/mzTab/blob/master/examples/1_1_Metabolomics_Draft/MTBLS263.mztab correct?
We have 
`SML 1022 79 | 523 CHEBI:25094 C6H14N2O2 null null Lysine`
linking down to 
`SMF 79 18 | 19 1 [M+H]+ null 147.1122` and
`SMF 523 18 | 19 1 [M+Na]+ null 169.0943 `
which has evidence by
`SME	18	1022	CHEBI:25094	C6H14N2O2	null	null	Lysine	null	null	[M+H]+	147.1122	1	147.1128	ms_run[1]:index=856 | ms_run[1]:index=872 | ms_run[1]:index=886 | ms_run[2]:index=856 | ms_run[2]:index=872 | ms_run[2]:index=888 | ms_run[3]:index=862 | ms_run[3]:index=876 | ms_run[3]:index=890 | ms_run[4]:index=836 | ms_run[4]:index=850 | ms_run[4]:index=864 | ms_run[5]:index=836 | ms_run[5]:index=850 | ms_run[5]:index=864 | ms_run[6]:index=834 | ms_run[6]:index=848 | ms_run[6]:index=862	[,,Progenesis MetaScope,]	[MS,MS,ms level,2]	53.8925	0	98.898	1	1282.28	1284`
and			
`SME 19 1022 CHEBI:25094 C6H14N2O2 null null Lysine null null [M+Na]+ 169.0943 1 169.0947 ms_run[1]:index=882 | ms_run[2]:index=870 | ms_run[3]:index=872 | ms_run[4]:index=846 | ms_run[5]:index=846 | ms_run[6]:index=854 [,,Progenesis MetaScope,] [MS,MS,ms level,2] 53.8925 0 98.898 1 1279.2 1284`

So we have one aggregate summary row for both adducts. 
Is there a use case to report these adducts as separate rows, even though they relate to the same metabolite?

**Comment by andrewrobertjones** [comment]
This looks to me like SMF 79 should link to SME 18 and SMF 523 to SME 19 but there is nothing to stop a reference to both evidence streams, and there could be a good reason to. Perhaps @jmrein  can comment?

**Comment by jmrein** [comment]
I agree, this SMF79 is based on SME18 and SMF523 on SME19. 

Same with the SMF6 and SMF937 pair.

**Comment by andrewrobertjones** [comment]
I think this just needs a change to the example file from @jmrein
