### ISSUE TITLE
6.2.25. study_variable_function[1-n] wrong example

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#97]
refers to PRIDE Ratio

**Comment by andrewrobertjones** [comment]
Fixed but needs a valid CV term @germa

**Comment by germa** [comment]
Added the following terms to the psi-ms.obo ontology:

[Term]
id: MS:1002882
name: study variable average function
def: "Function used to calculate the study variable quantification value." [PSI:PI]
is_a: MS:1001184 ! search statistics

[Term]
id: MS:1002883
name: median
def: "Median function." [PSI:PI]
is_a: MS:1002882 ! study variable average function

[Term]
id: MS:1002884
name: study variable variation function
def: "Function used to calculate the study variable quantification variation value." [PSI:PI]
is_a: MS:1001184 ! search statistics

[Term]
id: MS:1002885
name: standard error
def: "Standard error function." [PSI:PI]
is_a: MS:1002884 ! study variable variation function
