### ISSUE TITLE
question: log data an Coff. V.

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzTab#99]
If we have log scaled data. Should the Coff. of Variation be calculated using the standard formula on the log-transformed data or on the original data?

**Comment by oliveralka** [comment]
Consent on changing 6.3.18. abundance_coeffvar_study_variable [1-n] to a generic "statistical variable" which can be specified using a CV-Term.

**Comment by awd97** [comment]
Also, the default is now specified as 'arithmetic coefficient of variation' so it would be calculated on the original data

**Comment by andrewrobertjones** [comment]
Added CV terms for this into spec doc
